export const ADD_COMMENT = 'ADD_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const TOGGLE_IS_COMMENT_EDIT_STATUS = 'TOGGLE_IS_COMMENT_EDIT_STATUS'

export const FETCH_STATE_SUCCESS = 'FETCH_STATE_SUCCESS'
